apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: build-pipeline
spec:
  params:
  - name: platform
    type: string
    default: "linux/amd64"
  - name: git-url
    type: string
  - name: revision
    type: string  
    default: main
  - name: output-image
    value: quay.io/redhat-user-workloads/brianwcook-tenant/trusted-artifacts/my-component
  tasks:
    - name: clone-repository
      taskRef:
        resolver: bundles
        params:
        - name: name
          value: git-clone-oci-ta
        - name: bundle
          value: quay.io/redhat-appstudio-tekton-catalog/task-git-clone-oci-ta:0.1@sha256:e3490635200600da4a6b2997b0cf8e65e012155e7795824aa36d858a890ad31f
        - name: kind
          value: task
      params:
      - name: url
        value: "$(params.git-url)"
      - name: revision
        value: "$(params.revision)"
      - name: ociStorage
        value: "$(params.output-image).git"
      - name: ociArtifactExpiresAfter
        value: 5d
    - name: mpc-run-test
      params:
        - name: PLATFORM
          value: $(params.platform)
      runAfter:
      - clone-repository
      taskRef:
        resolver: git
        params:
        - name: url
          value: https://github.com/brianwcook/konflux-mpc-test-runner
        - name: revision
          value: main
        - name: pathInRepo
          value: test-runner.yaml



