apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: build-pipeline
spec:
  params:
  - name: platform
    type: string
    default: "linux/amd64"
  - name: git-url
    type: string
  - name: revision
    type: string  
    default: main
  - name: output-location
    value: quay.io/redhat-user-workloads/brianwcook-tenant/trusted-artifacts/my-component
  tasks:
    - name: init
      taskRef:
        resolver: bundles
        params:
        - name: name
          value: init
        - name: bundle
          value: quay.io/redhat-appstudio-tekton-catalog/task-init:0.2@sha256:686109bd8088258f73211618824aee5d3cf9e370f65fa3e85d361790a54260ef
        - name: kind
          value: task
      params:
      - name: image-url
        value: "$(params.output-image)"
      - name: rebuild
        value: "$(params.rebuild)"
      - name: skip-checks
        value: "$(params.skip-checks)"
    - name: clone-repository
      taskRef:
        resolver: bundles
        params:
        - name: name
          value: git-clone-oci-ta
        - name: bundle
          value: quay.io/redhat-appstudio-tekton-catalog/task-git-clone-oci-ta:0.1@sha256:e3490635200600da4a6b2997b0cf8e65e012155e7795824aa36d858a890ad31f
        - name: kind
          value: task
      when:
      - input: "$(tasks.init.results.build)"
        operator: in
        values:
        - 'true'
      runAfter:
      - init
      params:
      - name: url
        value: "$(params.git-url)"
      - name: revision
        value: "$(params.revision)"
      - name: ociStorage
        value: "$(params.output-image).$(context.pipeline.name)-git"
      - name: ociArtifactExpiresAfter
        value: 5d
      workspaces:
      - name: basic-auth
        workspace: git-auth
    - name: mpc-run-test
      params:
        - name: PLATFORM
          value: $(params.platform)
      taskRef:
        resolver: git
        params:
        - name: url
          value: https://github.com/brianwcook/konflux-mpc-test-runner
        - name: revision
          value: main
        - name: pathInRepo
          value: test-runner.yaml