apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: build-pipeline
spec:
  params:
  - name: platform
    type: string
    default: "linux/amd64"
  - name: git-url
    type: string
  - name: revision
    type: string  
    default: main
  - name: output-image
    value: quay.io/redhat-user-workloads/brianwcook-tenant/trusted-artifacts/my-component
  tasks:
    - name: init
      taskRef:
        resolver: bundles
        params:
        - name: name
          value: init
        - name: bundle
          value: quay.io/redhat-appstudio-tekton-catalog/task-init:0.2@sha256:686109bd8088258f73211618824aee5d3cf9e370f65fa3e85d361790a54260ef
        - name: kind
          value: task
      params:
      - name: image-url
        value: "$(params.output-image)"
      - name: skip-checks
        default: false
   