apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  creationTimestamp: null
  labels:
    appstudio.openshift.io/application: konflux-arm64-test-demo
    appstudio.openshift.io/component: arm64-test-demo
    pipelines.appstudio.openshift.io/type: build
  name: mpc-test-pipeline
  namespace: brianwcook-tenant
spec:
  params:
  - name: git-url
    type: string
    default: ""
  - name: revision
    default: "main"
    type: string
  - name: platform
    type: string
    default: "linux/amd64"
    description: architecture to execute the test pipeline on
  tasks:
    - name: init
      params:
        - name: pipelinerun-name
          value: $(context.pipelineRun.name)
        - name: pipelinerun-uid
          value: $(context.pipelineRun.uid)
      taskRef:
        params:
          - name: name
            value: init
          - name: bundle
            value: quay.io/redhat-appstudio-tekton-catalog/task-init:0.2@sha256:99674c6fbedcb153945ea37729c951e86314746cfc2dbeeecef6ce8b60229383
          - name: kind
            value: task
        resolver: bundles
    - name: build-container-arm64
      params:
        - name: PLATFORM
          value: linux/arm64
      runAfter:
        - init
      taskRef:
        resolver: git
        params:
        - name: url
          value: https://github.com/brianwcook/konflux-mpc-test-runner
        - name: revision
          value: main
        - name: pathInRepo
          value: test-runner.yaml
status: {}