apiVersion: tekton.dev/v1
kind: Task
metadata:
  annotations:
    tekton.dev/pipelines.minVersion: 0.12.1
    tekton.dev/tags: test, konflux
  labels:
    app.kubernetes.io/version: "0.1"
    build.appstudio.redhat.com/multi-platform-required: "true"
  name: test-runner-mpc
spec:
  description: test-runner-mpc
  params:
  - description: The platform to build on
    name: PLATFORM
    type: string
  stepTemplate:
    env:
    - name: BUILDER_IMAGE
      value: quay.io/bcook/jq-ubi9@sha256:a158a654d0c82556256090b7cbfd66db58c39b8f594d69ef8c420a1a1e0b3b77
    computeResources: {}
  steps:
  - env:
    - name: COMMIT_SHA
      value: "foo"
    image: quay.io/redhat-appstudio/multi-platform-runner:01c7670e81d5120347cf0ad13372742489985e5f@sha256:246adeaaba600e207131d63a7f706cffdcdc37d8f600c56187123ec62823ff44
    # per https://kubernetes.io/docs/concepts/containers/images/#imagepullpolicy-defaulting
    # the cluster will set imagePullPolicy to IfNotPresent
    name: build
    computeResources:
      limits:
        memory: 512Mi
      requests:
        cpu: 250m
        memory: 128Mi
    # the next script currently runs a bunch of stuff related to transferring workspace data, then rpm-ostree compose.  I need to make it run git clone, then execute the test script.
    script: |-
      set -o verbose
      set -eu
      set -o pipefail
      mkdir -p ~/.ssh
      if [ -e "/ssh/error" ]; then
        #no server could be provisioned
        cat /ssh/error
        exit 1
      elif [ -e "/ssh/otp" ]; then
       curl --cacert /ssh/otp-ca -XPOST -d @/ssh/otp $(cat /ssh/otp-server) >~/.ssh/id_rsa
       echo "" >> ~/.ssh/id_rsa
      else
        cp /ssh/id_rsa ~/.ssh
      fi
      chmod 0400 ~/.ssh/id_rsa
      export SSH_HOST=$(cat /ssh/host)
      export BUILD_DIR=$(cat /ssh/user-dir)
      export SSH_ARGS="-o StrictHostKeyChecking=no"
      mkdir -p scripts
      echo "$BUILD_DIR"
      ssh $SSH_ARGS "$SSH_HOST"  mkdir -p "$BUILD_DIR/workspaces" "$BUILD_DIR/scripts" "$BUILD_DIR/tmp"
      echo -e local arch is: $(arch)
      echo -e remote arch is:
      ssh $SSH_ARGS "$SSH_HOST" /bin/bash -c "arch"

      # transfers data
      # rsync -ra $(workspaces.source.path)/ "$SSH_HOST:$BUILD_DIR/workspaces/source/"
      
      # write the script to disk:
      cat >scripts/script-build.sh <<'REMOTESSHEOF'
      
      #!/bin/bash
      set -o verbose
      echo -e  $(uname -m)
      
      # cd $(workspaces.source.path)
      # if [ -z "$CONFIG_FILE" ] ; then
      #  CONFIG_FILE_ARG=""
      # else
      #  CONFIG_FILE_ARG="  --image-config=source/$CONFIG_FILE "
      #fi

      # rpm-ostree compose image --initialize --format oci $CONFIG_FILE_ARG "source/$IMAGE_FILE" rhtap-final-image
      
      REMOTESSHEOF
      
      # make it executable
      chmod +x scripts/script-build.sh
      
      # sync scripts dir to the SSH Host
      rsync -ra scripts "$SSH_HOST:$BUILD_DIR"
      
      # execute the script in a container on the SSH host
      ssh $SSH_ARGS "$SSH_HOST" podman  run \
      -e PARAM_BUILDER_IMAGE="quay.io/bcook/jq-ubi9:latest" \
      -v $BUILD_DIR/scripts:/script:Z \
      --user=0  --rm  "$BUILDER_IMAGE" /script/script-build.sh



      # this is all bringing data back.

      # rsync -ra "$SSH_HOST:$BUILD_DIR/workspaces/source/" "$(workspaces.source.path)/"
      # rsync -ra "$SSH_HOST:$BUILD_DIR/tekton-results/" "/tekton/results/"
      # buildah pull oci:rhtap-final-image
      # buildah images
      # buildah tag localhost/rhtap-final-image "$IMAGE"
      # container=$(buildah from --pull-never "$IMAGE")
      # buildah mount "$container" | tee /workspace/container_path
      # echo $container > /workspace/container_name

      # Hardcode result for now.
      RESULT=SUCCESS

    securityContext:
      capabilities:
        add:
        - SETFCAP
    volumeMounts:
    - mountPath: /workspace
      name: workspace
    - mountPath: /ssh
      name: ssh
      readOnly: true
  volumes:
  - emptyDir: {}
    name: workspace
  - name: ssh
    secret:
      optional: false
      secretName: multi-platform-ssh-$(context.taskRun.name)

